apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 8080
    name: http
  type: ClusterIP
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: web
        image: minikube.local:5000/dev/sample-api-svc
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: from_k8s_manifest_not_conjur
          - name: CUSTOM_MY_NAME
            valueFrom:
              configMapKeyRef:
                name: common
                key: custom-my-name
          - name: CUSTOM_MY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: common-secret
                key: custom-my-pass
          - name: CONJUR_VERSION
            value: "5"
          - name: CONJUR_APPLIANCE_URL
            value: "https://follower.dap.svc.cluster.local/api"
          - name: CONJUR_AUTHN_URL
            value: "https://follower.dap.svc.cluster.local/api/authn-k8s/minikube"
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_VERSION
            value: "5"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: conjur-certificate
                key: ssl-certificate
        command: ["/usr/local/bin/summon", "-f", "/etc/summon/secrets.yml"]
        args: ["java",
               "-ms512m",
               "-cp",
               "/app/resources:/app/classes:/app/libs/*",
               "net.vino9.sample.ResourceServerApplication"
        ]
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
          - mountPath: /etc/summon
            name: summon-config
            readOnly: true
      initContainers:
      - name: authenticator
        image: 'OCP_INTERNAL_REGISTRY/APP_NAME/conjur-kubernetes-authenticator:0.14.0'
        image: minikube.local:5000/dap/conjur-kubernetes-authenticator:0.14.0
        imagePullPolicy: Always
        env:
          - name: CONTAINER_MODE
            value: init
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_VERSION
            value: "5"
          - name: CONJUR_APPLICATIONLIANCE_URL
            value: "https://follower.dap.svc.cluster.local/api"
          - name: CONJUR_AUTHN_URL
            value: "https://follower.dap.svc.cluster.local/api/authn-k8s/minikube"
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/minikube/apps/default/*/*"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: conjur-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token

      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: summon-config
          configMap:
            name: summon-config
